{
 "title": "Cryptocurrency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Neo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"NEO\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"BTC\")\n  |> filter(fn: (r) => r[\"name\"] == \"Bitcoin\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"ETH\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cardano",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"ADA\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Stellar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"XLM\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Litecoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crypto_prices\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_price\")\n  |> filter(fn: (r) => r[\"crypto_key\"] == \"LTC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kafka message per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\"}[5m])"
    }
   ]
  },
  {
   "title": "Kafka Bytes Input per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\"}[5m])"
    }
   ]
  },
  {
   "title": "Kafka total messages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Kafka Input Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Conteneur Docker",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{job=\"docker\"}"
    }
   ]
  },
  {
   "title": "Kafka Output Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "CPU use per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"docker\"}[5m])"
    }
   ]
  }
 ]
}